name: snake_app
description: Classic Snake game built in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
  adaptive_icon_background: "#1B1B1B"
  adaptive_icon_foreground: "android/app/src/main/res/mipmap-hdpi/ic_launcher.png"

flutter_native_splash:
  color: "#1B1B1B"
  image: "android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
  android: true
  ios: true
  web: false